<a href="https://colab.research.google.com/github/kartikeyaGUPTA45/AUTOMATED-MACHINE-LEARNING/blob/master/POLYNOMIAL_REGRESSION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# 


















VISUALISING THE LINEAR REGRESSION RESULT

plt.scatter(X,Y, color='red')
plt.plot(X,lin_reg.predict(X),color='blue')
plt.title("Truth or Bluff(Linear Regression)")
plt.xlabel("Position Level")
plt.ylabel("Salary")
plt.show()

plt.scatter(X, Y, color = 'red')
plt.plot(X, lin_reg2.predict(poly_reg.fit_transform(X)), color = 'blue')
plt.title('Truth or Bluff (Polynomial Regression)')
plt.xlabel('Position level')
plt.ylabel('Salary')
plt.show()



# POLYNOMIAL LINEAR REGRESSION

# DATA PREPROCESSING

# IMPORTING THE LIBRARIES

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# IMPORTING THE DATASET

In [0]:

dataset=pd.read_csv("/content/Position_Salaries.csv")

In [3]:
print(dataset)

            Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000


In [0]:
X=dataset.iloc[: ,1:2].values



In [5]:
print(X)



[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [0]:
Y=dataset.iloc[: ,2].values



In [7]:
print(Y)

[  45000   50000   60000   80000  110000  150000  200000  300000  500000
 1000000]


# FITTING THE DATASET TO LINEAR REGRESSION(FOR COMPARISON)

In [0]:
from sklearn.linear_model import LinearRegression


In [9]:

lin_reg=LinearRegression()
lin_reg.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

# FITTING THE DATASET TO POLYNOMIAL REGRESSION



In [0]:
from sklearn.preprocessing import PolynomialFeatures



In [11]:
poly_reg=PolynomialFeatures(degree=4)
X_poly=poly_reg.fit_transform(X)
poly_reg.fit(X_poly,Y)



PolynomialFeatures(degree=4, include_bias=True, interaction_only=False,
                   order='C')

In [12]:
print(X_poly)


[[1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00]
 [1.000e+00 2.000e+00 4.000e+00 8.000e+00 1.600e+01]
 [1.000e+00 3.000e+00 9.000e+00 2.700e+01 8.100e+01]
 [1.000e+00 4.000e+00 1.600e+01 6.400e+01 2.560e+02]
 [1.000e+00 5.000e+00 2.500e+01 1.250e+02 6.250e+02]
 [1.000e+00 6.000e+00 3.600e+01 2.160e+02 1.296e+03]
 [1.000e+00 7.000e+00 4.900e+01 3.430e+02 2.401e+03]
 [1.000e+00 8.000e+00 6.400e+01 5.120e+02 4.096e+03]
 [1.000e+00 9.000e+00 8.100e+01 7.290e+02 6.561e+03]
 [1.000e+00 1.000e+01 1.000e+02 1.000e+03 1.000e+04]]


In [13]:

lin_reg2=LinearRegression()
lin_reg.fit(X_poly,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)