<a href="https://colab.research.google.com/github/kartikeyaGUPTA45/AUTOMATED-MACHINE-LEARNING/blob/master/Tree_Based_Pipeline_Optimization_Tool_(TPOT).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 

In [1]:
# Install tpot on the server
!pip install tpot

     |████████████████████████████████| 92kB 5.6MB/s 
     |████████████████████████████████| 163kB 14.5MB/s 
  Created wheel for stopit: filename=stopit-1.1.2-cp36-none-any.whl size=11956 sha256=d0d24a56d4e7097d441ce9b5374ffc32717204624e2a254ad93029b176dbaeb9
  Stored in directory: /root/.cache/pip/wheels/3c/85/2b/2580190404636bfc63e8de3dff629c03bb795021e1983a6cc7
Successfully built stopit


# IMPORTING LIBRARIES AND TPOT CLASSIFIER

In [4]:
import pandas as pd
import numpy as np
from tpot import TPOTClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# LOAD THE DATASET

In [5]:
iris = load_iris()


In [6]:
print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [9]:
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


# SPILITING THE DATASET INTO TRAINING AND TESTING

In [10]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target,
                                                    train_size=0.75, test_size=0.25)


In [11]:
print(X_train.shape)

(112, 4)


In [12]:
print(X_test.shape)

(38, 4)


In [14]:
print(y_train.shape)

(112,)


In [15]:
print(y_test.shape)

(38,)


# FITTING THE TPOT CLASSIFIER TO THE TRAINING DATA

In [16]:
tpot = TPOTClassifier(verbosity=2, max_time_mins=10)
tpot.fit(X_train, y_train)
print(tpot.score(X_test, y_test))


Generation 1 - Current best internal CV score: 0.9735177865612649
Generation 2 - Current best internal CV score: 0.9735177865612649
Generation 3 - Current best internal CV score: 0.9822134387351777
Generation 4 - Current best internal CV score: 0.9822134387351777
Generation 5 - Current best internal CV score: 0.9822134387351777
Generation 6 - Current best internal CV score: 0.9822134387351777
Generation 7 - Current best internal CV score: 0.9822134387351777
Generation 8 - Current best internal CV score: 0.9822134387351777
10.00 minutes have elapsed. TPOT will close down.
TPOT closed during evaluation in one generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: KNeighborsClassifier(SGDClassifier(input_matrix, alpha=0.0, eta0=0.1, fit_intercept=False, l1_ratio=1.0, learning_rate=invscaling, loss=log, penalty=elasticnet, power_t=0.5), n_neighbors=12, p=2, weights=uniform)
0.9210526315789473


In [17]:
print(tpot.fitted_pipeline_)


Pipeline(memory=None,
         steps=[('stackingestimator',
                 StackingEstimator(estimator=SGDClassifier(alpha=0.0,
                                                           average=False,
                                                           class_weight=None,
                                                           early_stopping=False,
                                                           epsilon=0.1,
                                                           eta0=0.1,
                                                           fit_intercept=False,
                                                           l1_ratio=1.0,
                                                           learning_rate='invscaling',
                                                           loss='log',
                                                           max_iter=1000,
                                                           n_iter_no_change=5,
                                

In [18]:
print(tpot.score(X_test, y_test))

0.9210526315789473
